# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  jira:
    runs-on: ubuntu-latest

    env:
     JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
     JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
     JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
     SERVICE_ID: ${{ secrets.SERVICE_ID }}

    steps:
    - name: Create Jira Issue and Report Deployment
      run: |
        RESPONSE=$(curl -s -X POST -H "Authorization: Basic $JIRA_API_TOKEN" -H "Content-Type: application/json" \
          -d '{ "fields": { "project": { "key": "AQ" }, "summary": "Change request", "issuetype": { "name": "[System] Change" } } }' \
          "$JIRA_BASE_URL/rest/api/2/issue/")
        echo $RESPONSE
        ISSUE_KEY=$(echo $RESPONSE | jq -r .key)
        
        RESPONSE=$(curl -s -X POST -H "Authorization: Bearer $JIRA_API_TOKEN" -H "Content-Type: application/json" \
          -d '{ "deployments": [ { "deploymentSequenceNumber": 1, "updateSequenceNumber": 1, "issueKeys": ["'"$ISSUE_KEY"'"], "state": "successful" } ] }' \
          "$JIRA_BASE_URL/rest/api/2/issue/$ISSUE_KEY/deployments")
        echo $RESPONSE
      shell: bash
